import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { absoluteUrl, LEGAL_NAME, SITE_NAME, SITE_URL } from "./lib/seo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const homeTitle = "Outpatient PHP & IOP in Costa Mesa | Live Clean & Focused";
const homeDescription =
  "An elevated approach to living clean and focused. PHP and IOP outpatient programs in Costa Mesa for adults ready to move forward with clarity.";

export const viewport: Viewport = {
  themeColor: "#03171d",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: homeTitle,
    template: "%s",
  },
  description: homeDescription,
  applicationName: SITE_NAME,
  authors: [{ name: LEGAL_NAME, url: SITE_URL }],
  creator: LEGAL_NAME,
  publisher: LEGAL_NAME,
  category: "Mental Health & Addiction Recovery",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    title: homeTitle,
    description: homeDescription,
    siteName: SITE_NAME,
    // Images are auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: homeTitle,
    description: homeDescription,
    // Images are auto-generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  // Icons are auto-generated by icon.tsx and apple-icon.tsx
  referrer: "strict-origin-when-cross-origin",
  formatDetection: {
    telephone: true,
    email: true,
    address: true,
  },
  verification: {
    // Add your verification tokens here when ready
    // google: "your-google-verification-code",
  },
};

// JSON-LD Structured Data for SEO
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "MedicalBusiness",
  name: LEGAL_NAME,
  description: homeDescription,
  url: SITE_URL,
  logo: absoluteUrl("/footprints-logo-no-back.png"),
  image: absoluteUrl("/opengraph-image"),
  telephone: "+1-949-350-1078",
  email: "info@footprintsrecovery.net",
  address: {
    "@type": "PostalAddress",
    streetAddress: "653 West 19th Street",
    addressLocality: "Costa Mesa",
    addressRegion: "CA",
    postalCode: "92627",
    addressCountry: "US",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: 33.6461,
    longitude: -117.9305,
  },
  openingHours: "Mo-Fr 09:30-16:00",
  priceRange: "$$",
  medicalSpecialty: [
    "Addiction Medicine",
    "Mental Health",
    "Substance Abuse Treatment",
  ],
  availableService: [
    {
      "@type": "MedicalTherapy",
      name: "Partial Hospitalization Program (PHP)",
      description: "Intensive day treatment program for addiction and mental health recovery",
    },
    {
      "@type": "MedicalTherapy",
      name: "Intensive Outpatient Program (IOP)",
      description: "Flexible outpatient treatment for addiction and mental health",
    },
    {
      "@type": "MedicalTherapy",
      name: "Dual Diagnosis Treatment",
      description: "Integrated treatment for co-occurring mental health and substance use disorders",
    },
  ],
  areaServed: {
    "@type": "GeoCircle",
    geoMidpoint: {
      "@type": "GeoCoordinates",
      latitude: 33.6461,
      longitude: -117.9305,
    },
    geoRadius: "50000",
  },
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
