import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const siteName = "Footprints In The Sand 2 Recovery Center";
const siteUrl = "https://footprintsinthesand.org";
const siteDescription =
  "At Footprints In The Sand 2 Recovery, our mission is to help people break free from the cycles that once controlled their lives with evidence-based PHP and IOP programming, relentless accountability, and multidisciplinary care.";

export const viewport: Viewport = {
  themeColor: "#03171d",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: siteName,
    template: `%s | ${siteName}`,
  },
  description: siteDescription,
  applicationName: siteName,
  keywords: [
    "Footprints In The Sand 2 Recovery",
    "addiction treatment",
    "PHP program",
    "IOP program",
    "dual diagnosis care",
    "trauma-informed therapy",
    "mental health recovery",
    "Costa Mesa rehab",
    "Orange County addiction treatment",
    "evidence-based recovery",
    "substance abuse treatment",
    "alcohol addiction",
    "drug rehabilitation",
  ],
  authors: [{ name: siteName, url: siteUrl }],
  creator: siteName,
  publisher: siteName,
  category: "Mental Health & Addiction Recovery",
  alternates: {
    canonical: siteUrl,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    title: siteName,
    description: siteDescription,
    siteName,
    // Images are auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: siteName,
    description: siteDescription,
    // Images are auto-generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  // Icons are auto-generated by icon.tsx and apple-icon.tsx
  referrer: "strict-origin-when-cross-origin",
  formatDetection: {
    telephone: true,
    email: true,
    address: true,
  },
  verification: {
    // Add your verification tokens here when ready
    // google: "your-google-verification-code",
  },
};

// JSON-LD Structured Data for SEO
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "MedicalBusiness",
  name: siteName,
  description: siteDescription,
  url: siteUrl,
  logo: `${siteUrl}/footprints-logo-no-back.png`,
  image: `${siteUrl}/opengraph-image`,
  telephone: "+1-949-350-1078",
  email: "info@footprintsrecovery.net",
  address: {
    "@type": "PostalAddress",
    streetAddress: "653 West 19th Street",
    addressLocality: "Costa Mesa",
    addressRegion: "CA",
    postalCode: "92627",
    addressCountry: "US",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: 33.6461,
    longitude: -117.9305,
  },
  openingHours: "Mo-Fr 09:30-16:00",
  priceRange: "$$",
  medicalSpecialty: [
    "Addiction Medicine",
    "Mental Health",
    "Substance Abuse Treatment",
  ],
  availableService: [
    {
      "@type": "MedicalTherapy",
      name: "Partial Hospitalization Program (PHP)",
      description: "Intensive day treatment program for addiction and mental health recovery",
    },
    {
      "@type": "MedicalTherapy",
      name: "Intensive Outpatient Program (IOP)",
      description: "Flexible outpatient treatment for addiction and mental health",
    },
    {
      "@type": "MedicalTherapy",
      name: "Dual Diagnosis Treatment",
      description: "Integrated treatment for co-occurring mental health and substance use disorders",
    },
  ],
  sameAs: [],
  areaServed: {
    "@type": "GeoCircle",
    geoMidpoint: {
      "@type": "GeoCoordinates",
      latitude: 33.6461,
      longitude: -117.9305,
    },
    geoRadius: "50000",
  },
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://www.google.com" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
